spring:
  datasource:
    url: jdbc:mysql://localhost/microservice01
    username: root
    password: Tiger@13
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
