spring:
  datasource:
    url: jdbc:mysql://localhost/microservice02
    username: root
    password: Tiger@13
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411  
    enabled: true
  sleuth:
    sampler:
      probability: 1.0  

management:
  endpoints:
    web:
      exposure:
        include: "*"  

server:
  port: 8084  

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
